
services:
  php:
    build: .
    restart: always
    ports:
      - "8000:80" # HTTP
      - "8001:443" # HTTPS
      - "8001:443/udp" # HTTP/3
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "zak.dev=127.0.0.1"
      - "zak.dev=::1"

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config: